# Generated by Django 5.2.4 on 2025-08-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_visit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
