# Generated by Django 5.2.5 on 2025-08-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_story_storyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='description',
        ),
        migrations.AddField(
            model_name='story',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='headline',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
